version: '3.9'
services:
  backend:
    build: ../backend
    environment:
      - PORT=5050
      - NODE_ENV=production
      - SKIP_DB=true
      - ALLOW_START_WITHOUT_DB=true
    expose:
      - "5050"
  frontend:
    build: ../frontend
    environment:
      - VITE_API_BASE=http://nginx/api
    expose:
      - "5173"
  nginx:
    image: nginx:1.27
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

